### ISSUE TITLE
Issue with kmip server IP

### ISSUE THREAD

**Issue by TomerYakir** [pkdone/MongoSecurityPlaypen#2]
My centralit VM was created with IP: 10.0.2.15, so the pykmip_server.py had to be changed accordingly

**Comment by TomerYakir** [comment]
Note you can specify 0.0.0.0 as the IP so it'll listen on all addresses

**Comment by TomerYakir** [comment]
Disregard - the root cause is that vagrant failed to assign proper IPs to the nodes

**Comment by pkdone** [comment]
Hi @TomerYakir 
How did you fix Vagrant to assign the correct addresses?

Vagrantfile has:
        centralit.vm.hostname = "centralit.vagrant.dev"
        centralit.vm.network :private_network, ip: "192.168.14.100"

So hopefully 192.168.14.100 was assigned to the VM for you?
Paul

**Comment by TomerYakir** [comment]
Hi @pkdone,

Actually I closed the case too soon.
What happens is that the host-only adapter's IP gets automatically cleared after a while.
I think it may be related to the NetworkManager service on the VM.

Have you ever came across this issue?

I think this may be related:
http://serverfault.com/questions/514340/interface-ip-address-is-removed-automatically-on-centos-running-inside-virtualbo

**Comment by TomerYakir** [comment]
BTW, the network-scripts/ifcfg-enp0s8 looks fine:
```
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
NM_CONTROLLED=no
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.14.100
NETMASK=255.255.255.0
DEVICE=enp0s8
PEERDNS=no
#VAGRANT-END
```

**Comment by TomerYakir** [comment]
I think I've found a workaround - run `sudo ifup enp0s8` after the machine starts

**Comment by TomerYakir** [comment]
Worked around using this yaml:
```
- name: Bring up the internal network
  hosts: all
  become: yes
  become_method: sudo
  tasks:
   - name: run ifup
     command: ifup enp0s8
   - name: stop NM
     command: chkconfig NetworkManager off
   - name: chkconfig network 
     command: chkconfig network on
   - name: stop NM service
     command: service NetworkManager stop
   - name: restart network
     command: service network restart 
```
